language: python

python:
  - '2.7'

branches:
  except:
    - gh-pages

env:
  - TOX_ENV=py27

before_install:
  - sudo apt-get -qq update
  - python -m pip install -U pip
  - python -m easy_install -U setuptools

install:
  - pip install codecov
  - pip install tox

script:
  - tox -e $TOX_ENV

after_success:
  - codecov

