language: python

python:
  - '2.7'

branches:
  except:
    - gh-pages

env:
  - TOX_ENV=py27

install:
  - pip install codecov
  - pip install tox

script:
  - tox -e $TOX_ENV

after_success:
  - codecov

