---
language: python
python:
  - '2.7'
branches:
  except:
    - gh-pages
before_install:
  - sudo apt-get -qq update
install:
  - pip install tox-travis
  - pip install codecov
script:
  - tox
after_success:
  - codecov
notifications:
  irc:
    channels:
      - "ircs://irc1.terahertz.net:6697/#bgpfu"
    on_success: change
    on_failure: always
    skip_join: true
