---
environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"

build: false

install:
  - "%PYTHON%/Scripts/pip.exe install -r facsimile/requirements-test.txt"
  - "%PYTHON%/Scripts/pip.exe install tox"
  - "%PYTHON%/Scripts/pip.exe install codecov"

test_script:
  - "%PYTHON%/Scripts/tox.exe -e py"

...